version: '3.0'
services:
  api:
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - 'mysql'
        # condition: 'service_healthy'
    volumes:
      - './:/app'
        
  mysql:
    image: mysql
    container_name: mysql_service
    volumes:
        - ./mysql:/var/lib/mysql/
    environment:
        MYSQL_ROOT_PASSWORD: "high0426@@"
        MYSQL_DATABASE: "wanted"
#            MYSQL_USER: "user"
#            MYSQL_PASSWORD: "password"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
        - "3306:3306"